/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 255987f2bb3ecafc19c3a9a8f3188ac2)
interface __BaseEnv_Env {
	INVOICES_BUCKET: R2Bucket;
	DB: D1Database;
	JWT_SECRET: string;
	GEMINI_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./server/src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "JWT_SECRET" | "GEMINI_API_KEY">> {}
}
